const reportApi=async(path,options={})=>{const r=await fetch(`/api/teacher${path}`,{headers:{"Content-Type":"application/json"},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"حدث خطأ");return d};
const e=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let reportSettings=null;
async function loadSettings(){if(!reportSettings)reportSettings=await reportApi('/preferences/reports');return reportSettings}
function fields(s,prefix='rs'){return `<div class="form-grid"><div class="field">اسم المدرسة<input id="${prefix}School" value="${e(s.schoolName)}"></div><div class="field">إدارة التعليم<input id="${prefix}Dept" value="${e(s.educationDepartment)}"></div><div class="field">مكتب التعليم (اختياري)<input id="${prefix}Office" value="${e(s.educationOffice)}"></div><div class="field">اسم المعلمة<input id="${prefix}Teacher" value="${e(s.teacherName)}"></div><div class="field">العام الدراسي<input id="${prefix}Year" value="${e(s.academicYear)}" placeholder="1448هـ"></div><div class="field">اسم مديرة المدرسة (اختياري)<input id="${prefix}Principal" value="${e(s.principalName)}"></div></div>`}
function read(prefix='rs'){return{schoolName:document.getElementById(`${prefix}School`)?.value.trim()||'',educationDepartment:document.getElementById(`${prefix}Dept`)?.value.trim()||'',educationOffice:document.getElementById(`${prefix}Office`)?.value.trim()||'',teacherName:document.getElementById(`${prefix}Teacher`)?.value.trim()||'',academicYear:document.getElementById(`${prefix}Year`)?.value.trim()||'',principalName:document.getElementById(`${prefix}Principal`)?.value.trim()||''}}
async function renderReportSettings(){const content=document.getElementById('content');if(location.hash!=='#settings'||!content)return;const s=await loadSettings();content.innerHTML=`<div class="card" style="max-width:760px"><h3 class="section-title">بيانات التقارير والطباعة</h3><p style="font-size:.85rem;color:var(--muted)">تُحفظ هذه البيانات مرة واحدة وتظهر تلقائيًا في جميع ملفات المتابعة والاختبارات.</p><div id="reportSettingsMsg"></div>${fields(s)}<button class="btn btn-primary" id="saveReportSettings" style="margin-top:16px">حفظ الإعدادات</button></div>`;document.getElementById('saveReportSettings').onclick=async()=>{const box=document.getElementById('reportSettingsMsg');try{reportSettings=await reportApi('/preferences/reports',{method:'PUT',body:JSON.stringify(read())});box.innerHTML='<div class="form-success" style="margin-bottom:14px">تم حفظ بيانات الطباعة بنجاح.</div>'}catch(err){box.innerHTML=`<div class="form-error" style="margin-bottom:14px">${e(err.message)}</div>`}}}
function openTemporaryPrint(url,title){loadSettings().then(s=>{const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modal-overlay" id="reportPrintOverlay"><div class="modal-box"><h3>معاينة قبل الطباعة</h3><p style="font-size:.82rem;color:var(--muted)">يمكن تعديل هذه النسخة مؤقتًا، ولن تتغير الإعدادات المحفوظة.</p>${fields(s,'tmp')}<div class="field" style="margin-top:10px">عنوان المستند<input id="tmpTitle" value="${e(title)}"></div><div class="modal-actions"><button class="btn btn-outline" id="cancelTmpPrint">إلغاء</button><button class="btn btn-primary" id="openTmpPrint">فتح المعاينة</button></div></div></div>`;document.getElementById('cancelTmpPrint').onclick=()=>root.innerHTML='';document.getElementById('reportPrintOverlay').onclick=x=>{if(x.target.id==='reportPrintOverlay')root.innerHTML=''};document.getElementById('openTmpPrint').onclick=()=>{const q=new URLSearchParams({...read('tmp'),title:document.getElementById('tmpTitle').value.trim()});window.open(`${url}${url.includes('?')?'&':'?'}${q}`,'_blank');root.innerHTML=''}})}
function enhance(){if(location.hash==='#settings')setTimeout(renderReportSettings,60);document.querySelectorAll('a[href*="/reports/student/"][href$=".pdf"]').forEach(a=>{if(a.dataset.reportReady)return;a.dataset.reportReady='1';a.textContent='معاينة وطباعة PDF';a.onclick=x=>{x.preventDefault();openTemporaryPrint(a.getAttribute('href').replace('.pdf','/print'),'سجل متابعة الطالبة')}});document.querySelectorAll('#repClassLink').forEach(a=>{if(a.dataset.reportReady)return;a.dataset.reportReady='1';a.textContent='معاينة وطباعة تقرير الفصل';a.removeAttribute('target');a.onclick=x=>{x.preventDefault();const id=document.getElementById('repClass')?.value||'';openTemporaryPrint(`/api/teacher/reports/class/print?classId=${encodeURIComponent(id)}`,'كشف متابعة الفصل')}});document.querySelectorAll('[data-results]').forEach(btn=>{const cell=btn.parentElement;if(!cell||cell.querySelector('.print-test-btn'))return;const p=document.createElement('button');p.className='btn btn-outline btn-sm print-test-btn';p.textContent='طباعة';p.onclick=()=>openTemporaryPrint(`/api/teacher/reports/test/${btn.dataset.results}/print`,'اختبار');cell.insertBefore(p,cell.lastElementChild)})}
const obs=new MutationObserver(enhance);obs.observe(document.body,{subtree:true,childList:true});window.addEventListener('hashchange',enhance);enhance();
